ml: 1.0 # 负载质量 (kg) - 被吊挂物体的质量
g: 9.81 # 重力加速度 (m/s²) - 地球重力常数

# 系统维度参数
nxl: 13 # 负载状态向量维度: 位置3 + 速度3 + 四元数4 + 角速度3 = 13
nul: 18 # 控制输入向量维度: 通常包含力、力矩和零空间控制量
nWl: 6 # 力和力矩向量维度: 力3维 + 力矩3维 = 6
nq: 6 # 无人机数量

# 几何参数
ez: [0, 0, 1] # Z轴单位向量 - 表示重力方向，用于计算重力补偿

# 空间变换矩阵 (3x3)
# 用于将重力力矩从惯性系转换到体坐标系
# 通常与负载的几何形状和质量分布相关
S_rg:
  - [0, 0, 0]
  - [0, 0, 0]
  - [0, 0, 0]

# 环境参数
envs: 1 # 环境数量 - 用于并行仿真或训练

horizon: 100 # 轨迹步数，根据你的实际需求设置
dt: 0.04 # 步长（如果还没有的话）
